name: echo tag oh push tag

on:
  push:
    tags:
      - '*'

jobs:
  echo_tag_on_push_tag:
    name: "Echo tag"
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACTIONS_RUNNER_APP_ID }}
          private_key: ${{ secrets.ACTIONS_RUNNER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: echo tag
        run: |
          echo ${{ github.ref_name }}
      # - name: dump github context
      #   run: |
      #     echo ${{ toJson(github) }}
