name: request reviews

on:
  pull_request:
    types:
      - review_requested

jobs:
  echo_reviewers:
    name: echo_reviewers
    runs-on: ubuntu-latest
    steps:
      - name: echo reviewers
        run: |
          echo ${{ toJSON(github.event.pull_request.requested_reviewers) }}
          echo ${{ toJSON(github.event.pull_request.requested_teams) }}
