name: tag sha on push

on:
  push:
    branches:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Git SHA'
        required: true

jobs:
  echo_head_ref:
    name: echo_sha_on_push
    runs-on: ubuntu-latest
    steps:
      - name: echo sha
        run: |
          echo "${{ github.event.before }} -> ${{ github.event.after || github.event.inputs.sha }}"
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACTIONS_RUNNER_APP_ID }}
          private_key: ${{ secrets.ACTIONS_RUNNER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: tag sha
        run: |
          git tag tag-${{ github.event.after || github.event.inputs.sha }}
          git push origin tag-${{ github.event.after || github.event.inputs.sha }}

